config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/gallery', to: 'cakes#index'
  get '/order', to: 'pages#order'
  get '/admin', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
  resources :cakes, only: [:create, :new, :destroy]
end

app/models/cake.rb
class Cake < ActiveRecord::Base
  belongs_to :category
  mount_uploader :cake, CakeUploader
  validates_presence_of :cake
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cakes
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :username, :password
  validates_uniqueness_of :username
  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  before_action :require_user, only: [:new, :create, :destroy]
  
  def index
    @categories = Category.all
    @cakes = Category.find(params[:category_id]).cakes
  end
  
  def new
    @cake = Cake.new
  end
  
  def create
    @cake = Cake.new(cake_params)
    
    if @cake.save
      redirect_to gallery_path 
    else
      render :new
    end
  end
  
  def destroy
    cake = Cake.find(params[:id])
    cake.destroy
    redirect_to gallery_path
  end
  
  private
  def cake_params
    params.require(:cake).permit(:cake, :category_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def contact
  end
  
  def order
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(username: params[:username])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to gallery_path
    else
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cakes/index.html.erb
<header>
  <div class="header">
    <a href="#" class="menu-toggle">Categories</a>
  </div>
  <nav class="main-nav">
    <ul>
      <% @categories.each do |category| %>
      <li><%= link_to "#{category.name}", gallery_path(category_id: category.id), class: "#{'active' if params[:category_id] == category.id.to_s}" %></li>
      <% end %>
    </ul>
  </nav>
</header>

<% provide(:page, "gallery") %>
<ul id="gallery">
  <% @cakes.each do |cake| %>
    <li>
      <%= image_tag(cake.cake_url, class: "gallery-image") %>
      <% if logged_in? %>
        <%= link_to "Delete", cake_path(cake), method: :delete %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to "New Cake", new_cake_path, class: "button" %>
<% end %>

app/views/cakes/new.html.erb
<h1>New Cake:</h1>
<%= form_for @cake do |f| %>
  <%= f.file_field :cake %>
  <%= f.hidden_field :cake_cache %>
  <br>
  <br>
  <%= f.select :category_id, Category.all.map { |n| [n.name, n.id]} %>
  <br>
  <br>
  <%= submit_tag "Save Cake", class: "button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jills Mixing Bowl</title>
  <link href='https://fonts.googleapis.com/css?family=Ultra|Slabo+13px' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'shared/header' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'shared/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:page, "about") %>
<img src="img/about_cake.jpg" id="hero_cake">
  <div id="hero">
    <h2>How I started...</h2>
    <p>Thank you for visting my website and taking interest in my work. My name is Jill Beck and I am a cake and sugar artist. I was born and raised in Hubbard, Ohio. I love to create special custom cakes and fondant figures specially made for my customers.</p>
    <p>My grandma and mother have been a huge influence in my cake making and decorating abilities. Both my mother and grandmother made cakes for many years and still do to this day, they have inspired me to follow my dreams of opening my own cake business! I spend countless hours on all my creations to make sure they are perfect, I love to create new things daily and hope my passion will inspire other cake artists to follow their dreams also...</p>
  </div>
</div>

app/views/pages/contact.html.erb
<% provide(:page, "contact") %>
<script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
<img src="img/contact_cake.jpg" id="hero_cake">
<div id="contact-info">
  <div style="height: 500px;max-width:100%;list-style:none; transition: none;overflow:hidden;" class="gmap_canvas"><div id="embed-map-display" style="height:100%; width:100%;max-width:100%;"><iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=3309+Pothour+Wheeler+Rd.+Hubbard,+Ohio,+44425&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe></div><a class="google-map-code-enabler" rel="nofollow" href="http://www.dog-checks.com" id="get-data-for-embed-map">dog checks</a><style>#embed-map-display img{max-width:none!important;background:none!important;font-size: inherit;}</style></div><script src="https://www.dog-checks.com/google-maps-authorization.js?id=c6243cbb-daa4-501f-fd39-8bfe72ae7c6e&c=google-map-code-enabler&u=1463966257" defer="defer" async="async"></script>
  <div id="contact-info-secondary">
    <h3>Jills Mixing Bowl</h3>
    <h3>
      Address: 3309 Pothour Wheeler Rd.<br>
      Hubbard, Ohio, 44225
    </h3>
    <h3>Phone: 330-646-1194</h3>
    <h3>Email: jmixingbowl@gmail.com</h3>
  </div>
</div>

app/views/pages/home.html.erb
<% provide(:page, "home") %>
<img src="img/hero_cake.jpg" id="hero_cake">
<div id="hero">
  <h2>Welcome!</h2>
  <p>Welcome to Jill&#39;s Mixing Bowl! I am a home based baker who specializes in custom cakes, cupcakes and sugar art! Let us help you create a one of a kind design tailored to your event! From stunning wedding cakes, to amazing birthday cakes and all special occasions, we strive to make sure your special day is remembered with a very special cake! All of our cakes and cupcakes are made to order, please contact us today to place an order for your one of a kind cake!
  </p>
  <p>
Become a fan and follow us on Facebook or Instagram! Our Facebook fan page and Instagram is updated weekly with our latest creations! Please browse our photo gallery to see what we can do for you!</p>
  <div id="call_to_action">
    <a target="_blank" href="https://www.facebook.com/Jills-Mixing-Bowl-758019187568572/" class="button">Facebook</a>
    <a target="_blank" href="https://www.instagram.com/jills_mixing_bowl/" class="button">Instagram</a>
  </div>
</div>

app/views/pages/order.html.erb
<% provide(:page, "order") %>
<div class="order">
  <h2>Order Here</h2>
  <p>I happily take custom orders for parties, weddings and special occasions. Please try to place orders at least a month in advance as I am  in very high  demand. When placing an order I do require a deposit that is half the price of the cake. The deposit must be received within a week that the order was placed in order to secure the date. I also make fondant figures to place on personal cakes that you might want to bake yourself! Fondant figures have to take at least a week to dry to ensure they are a quality product! Please also visit me on facebook to see the latest that is happening with Jill&#39;s Mixing Bowl!</p>
  <h3>Call:</h3>
  <h4>330-646-1194</h4>
  <h3>Email:</h3>
  <h4>jmixingbowl@gmail.com</h4>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <h2>Order</h2>
  <p>330-646-1194</p>
  <p>jmixingbowl@gmail.com</p>
</footer>
<footer class="footer">
  <h2>Address</h2>
  <p>3309 Pothour Wheeler Rd.</p>
  <p>Hubbard, Ohio, 44425</p>
</footer>
<footer class="footer">
  <h2>Follow Us</h2>
  <a target="_blank" href="https://www.facebook.com/Jills-Mixing-Bowl-758019187568572/">
    <img src="img/facebook-logo.png" class="social-icon">
  </a>
  <a target="_blank" href="https://www.instagram.com/jills_mixing_bowl/">
    <img src="/img/instagram-photo.png" class="social-icon">
  </a>
</footer>

app/views/shared/_header.html.erb
<h1>Jill&#39;s Mixing Bowl</h1>
<header>
  <div class="header">
    <a href="#" class="menu-toggle">Menu</a>
  </div>
  <nav class="main-nav">
    <ul>
      <li><%= link_to "Home", root_path, class: "#{"active" if yield(:page) == "home" }" %></li>
      <li><%= link_to "About", about_path, class: "#{"active" if yield(:page) == "about" }" %></li>
      <li><%= link_to "Contact", contact_path, class: "#{"active" if yield(:page) == "contact" }" %></li>
      <li><%= link_to "Gallery", gallery_path(category_id: 1), class: "#{"active" if yield(:page) == "gallery" }" %></li>
      <li><%= link_to "Order", order_path, class: "#{"active" if yield(:page) == "order" }" %></li>
      
      <% if logged_in? %>
        <li><%= link_to "Sign Out", sign_out_path %></li>
      <% end %>
    </ul>
  </nav>
</header>